# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'authorization.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.text_about_authorization = QtWidgets.QLabel(self.centralwidget)
        self.text_about_authorization.setGeometry(QtCore.QRect(330, 140, 351, 21))
        self.text_about_authorization.setObjectName("text_about_authorization")
        self.authorization = QtWidgets.QLabel(self.centralwidget)
        self.authorization.setGeometry(QtCore.QRect(330, 80, 261, 61))
        self.authorization.setObjectName("authorization")
        self.login = QtWidgets.QPushButton(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(330, 170, 131, 28))
        self.login.setObjectName("login")
        self.registration = QtWidgets.QPushButton(self.centralwidget)
        self.registration.setGeometry(QtCore.QRect(470, 170, 131, 28))
        self.registration.setObjectName("registration")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 40, 581, 41))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.text_about_authorization.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Хотите войти или зарегистрироваться?</span></p></body></html>"))
        self.authorization.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Авторизация</span></p></body></html>"))
        self.login.setText(_translate("MainWindow", "Войти"))
        self.registration.setText(_translate("MainWindow", "Регистрация"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Дневник выполнения спортивных задач</span></p></body></html>"))
