# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(877, 812)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(10, 70, 771, 301))
        self.table.setObjectName("table")
        self.table.setColumnCount(4)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 771, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.delete_entry_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.delete_entry_2.setObjectName("delete_entry_2")
        self.horizontalLayout_2.addWidget(self.delete_entry_2)
        self.new_entry_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.new_entry_2.setObjectName("new_entry_2")
        self.horizontalLayout_2.addWidget(self.new_entry_2)
        self.new_task_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.new_task_2.setObjectName("new_task_2")
        self.horizontalLayout_2.addWidget(self.new_task_2)
        self.open_task_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.open_task_2.setObjectName("open_task_2")
        self.horizontalLayout_2.addWidget(self.open_task_2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 400, 141, 41))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(180, 410, 201, 22))
        self.comboBox.setObjectName("comboBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 877, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Результат"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Дата"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Оценка результата"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Комментарий к результату"))
        self.delete_entry_2.setText(_translate("MainWindow", "Удалить запись"))
        self.new_entry_2.setText(_translate("MainWindow", "Новая запись"))
        self.new_task_2.setText(_translate("MainWindow", "Новая задача"))
        self.open_task_2.setText(_translate("MainWindow", "Открыть задачу"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Открыть задачу:</span></p></body></html>"))
